package de.echsecutables.rollandbuild.models;

import io.swagger.annotations.ApiModel;

@ApiModel(description = "Enumerates the 4 Rotations in 2d generated by a 90 degree (pi/2) turn.")
public enum Orientation {
    ORIGINAL, // Not turned
    CLOCKWISE, // turned by - pi/2
    COUNTERCLOCKWISE, // turned by pi/2
    HALF // turned by pi
}
